# Numpy

Numpy es la principal librería para la computación científica en Python. Algunas
librerías como pandas, SciPy, Matplotlib, TensorFlow, entre otros están construídas
sobre las bases de Numpy.

Cualquier persona que utilice números en Python, deberá utilizar Numpy. Para 
comenzar, debemos comprender que son los Numpy Array:

![Numpy Array](numpy_array.png)

Los arrays son similares a una lista de Python, sin embargo tienen una gran 
diferencia y es que este tipo de dato solo acepta valores del mismo tipo: array
de enteros, array de flotantes, array de complejos, etc.

Adicionalmente los arrays pueden ser de 1 dimensión, 2 dimensiones, 3 dimensiones.
(ver la imagen de arriba)

In [1]:
!pip install numpy

In [2]:
# Importación de libreria numpy
import numpy as np

# Version
print(f"Numpy version: {np.__version__}")

Numpy version: 2.0.2


In [3]:
# Array de ceros
ceros = np.zeros(10)
print(ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
unos = np.ones(3)
print(unos)

[1. 1. 1.]


In [4]:
# Array de aleatorios
aleatorios = np.random.rand(10)
print(aleatorios)

[0.65452018 0.52188724 0.89948164 0.44582302 0.09083147 0.13875106
 0.70521583 0.34212469 0.48157665 0.50721853]


In [4]:
np.random.random(10)

array([0.65789603, 0.66196175, 0.39660592, 0.23442071, 0.7644638 ,
       0.24691773, 0.15798679, 0.70410351, 0.95771276, 0.75714494])

## Operaciones básicas con arreglos

In [6]:
array = np.array([1, 2, 3, 4, 5])
print(type(array))
print("Array:", array)

# Array operations
print("Suma:", np.sum(array))
print("Promedio:", np.mean(array))
print("Cuadrados:", array ** 2)
print("Raices:", np.sqrt(array))
print("Mínimo:", np.min(array))
print("Máximo:", np.max(array))

<class 'numpy.ndarray'>
Array: [1 2 3 4 5]
Suma: 15
Promedio: 3.0
Cuadrados: [ 1  4  9 16 25]
Raices: [1.         1.41421356 1.73205081 2.         2.23606798]
Mínimo: 1
Máximo: 5


In [9]:
matriz = np.array([[1,2],[3,4]])
matriz ** 2

array([[ 1,  4],
       [ 9, 16]])

In [7]:
lista = [1, 2, 3, 4, 5]
print(type(lista))
print("Lista:", lista)

print("Suma:", sum(lista))
print("Promedio:", sum(lista) / len(lista))
print("Cuadrados:", [x ** 2 for x in lista]) # list comprehension
print("Raices:", [x ** 0.5 for x in lista])
print("Mínimo:", min(lista))
print("Máximo:", max(lista))

<class 'list'>
Lista: [1, 2, 3, 4, 5]
Suma: 15
Promedio: 3.0
Cuadrados: [1, 4, 9, 16, 25]
Raices: [1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979]
Mínimo: 1
Máximo: 5


### Operaciones entre arreglos

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Operaciones elemento a elemento
print(a + b)  # [5, 7, 9]
print(a - b)  # [-3, -3, -3]
print(a * b)  # [4, 10, 18]
print(a / b)  # [0.25, 0.4, 0.5]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


### Funciones matemáticas

In [8]:
# Funciones trigonométricas
print(np.sin(a))  # Seno de cada elemento

# Funciones exponenciales y logarítmicas
print(np.exp(a))  # Exponencial (e^x) de cada elemento
print(np.log(a))  # Logaritmo natural de cada elemento

[0.84147098 0.90929743 0.14112001]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]


## Array de más dimensiones

In [9]:
# Arreglo de números enteros
arreglo = np.arange(1, 11)
print(arreglo)

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
# Arreglo 2x3 de ceros
ceros_2 = np.zeros((2, 3))
print(ceros_2)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# Arreglo 2x2 de aleatorios
aleatorios_2 = np.random.random((2, 4))
print(aleatorios_2)

[[0.23151029 0.34692598 0.30724146 0.00932505]
 [0.34080525 0.12100666 0.48936887 0.74538449]]


Matrix

![Numpy Matrix](numpy_matrix.png)

In [12]:
# Arreglo 3x3 de unos
unos = np.ones((3, 3))
ceros = np.zeros((3, 3))
aleatorios = np.random.random((3, 3))

tensor = np.array([unos, ceros, aleatorios])
print(tensor)

[[[1.         1.         1.        ]
  [1.         1.         1.        ]
  [1.         1.         1.        ]]

 [[0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.85886591 0.75013717 0.15540832]
  [0.99432589 0.42469958 0.60619581]
  [0.14808781 0.25044948 0.58610372]]]


Tensor

![Numpy Tensor](numpy_tensor.png)

## Atributo `shape`

In [13]:
# Tamaño de un array
aleatorios.shape

(3, 3)

In [14]:
# Tamaño de una matriz
aleatorios_2.shape

(2, 4)

In [15]:
# Tamaño de un tensor
tensor.shape

(3, 3, 3)

## Métodos `flatten` y `reshape`

In [10]:
np.array([[1,2], [5,7], [6,6]])

array([[1, 2],
       [5, 7],
       [6, 6]])

In [16]:
arreglo = np.array([[1,2], [5,7], [6,6]])
arreglo.shape

(3, 2)

In [17]:
arreglo.flatten()

array([1, 2, 5, 7, 6, 6])

In [18]:
arreglo.reshape((2, 3))

array([[1, 2, 5],
       [7, 6, 6]])

In [19]:
# Conversión de lista a arreglo
sudoku_list = [[0, 0, 4, 3, 0, 0, 2, 0, 9],
 [0, 0, 5, 0, 0, 9, 0, 0, 1],
 [0, 7, 0, 0, 6, 0, 0, 4, 3],
 [0, 0, 6, 0, 0, 2, 0, 8, 7],
 [1, 9, 0, 0, 0, 7, 4, 0, 0],
 [0, 5, 0, 0, 8, 3, 0, 0, 0],
 [6, 0, 0, 0, 0, 0, 1, 0, 5],
 [0, 0, 3, 5, 0, 8, 6, 9, 0],
 [0, 4, 2, 9, 1, 0, 3, 0, 0]]

type(sudoku_list)

list

### Actividad

Movimiento parabólico:
- Posición horizontal: $x(t) = v_0 \cdot \cos(\theta) \cdot t$
- Posición vertical: $y(t) = v_0 \cdot \sin(\theta) \cdot t - \frac{1}{2} g t^2$
- Donde:
    - $v_0$: Es la velocidad inicial en $m/s$
    - $\theta$: ángulo de lanzamiento (grados)
    - $g$: aceleración debido a la gravedad ($9.81 \, m/s$)
    - $t$: tiempo en segundos


Dado lo siguiente:
- velocidad inicial: $20 \, m/s$
- ángulo de lanzamiento: $45ª$
- tiempo de vuelo: $ 4\, s$

Realizar:
- Cálculo de la posición horizontal y vertical
- Crear un arreglo de 100 posiciones con ayuda de `np.linspace` para el tiempo
de vuelo definido.
- Graficar la trayectoria de vuelo con ayuda de `matplotlib`